import { buildLesson } from "./helper.mjs";

const PART = "Part 8: Regression and Correlation";

export const topics = [
  buildLesson({
    title: "Scatter Plots and Correlation",
    partLabel: PART,
    principles: [
      "Scatter plots reveal form, direction, strength, outliers",
      "Pearson r measures linear association",
      "|r| near 1 ⇒ tight linear cloud",
      "Always plot before trusting r",
    ],
    objectives: [
      "Read scatter plots",
      "Compute/interpret r",
      "Spot nonlinear patterns where r misleads",
      "Flag influential points",
    ],
    why: "First look at bivariate quantitative data — features vs labels, spend vs revenue.",
    idea: "r > 0 upward trend; r < 0 downward; r≈0 no linear trend (maybe still curved).",
    steps: [
      { title: "Plot y vs x", body: "Eyes first." },
      { title: "Describe form", body: "Linear? curved? clusters?" },
      { title: "Summarize with r", body: "If roughly linear." },
    ],
    example: "Hours studied vs score: upward cloud, r=0.7 — moderately strong positive linear association.",
    labCue: "**regression** lab — drag points; live r.",
    check: ["Can r=0 with clear dependence?", "Effect of one outlier on r?"],
    formal: "r = Sxy / √(Sxx Syy) = sample correlation.",
    formulas: "- r ∈ [-1,1]\n- r = Cov̂/(s_x s_y)",
    pitfalls: ["Using r alone without a plot", "Causation claims"],
  }),

  buildLesson({
    title: "Simple Linear Regression",
    partLabel: PART,
    principles: [
      "Model: Y ≈ β₀ + β₁X + error",
      "Least squares minimizes Σ residuals²",
      "Closed form for slope and intercept",
      "Fitted line is a prediction machine — not magic truth",
    ],
    objectives: [
      "State the SLR model",
      "Compute β̂₁, β̂₀",
      "Predict ŷ for a new x",
      "Explain least squares criterion",
    ],
    why: "The workhorse predictive model and the gateway to ML linear models.",
    idea: "Choose the line that makes vertical mistakes as small as possible in squared length.",
    steps: [
      { title: "Compute means and sums of squares", body: "Sxx, Sxy." },
      { title: "Slope", body: "β̂₁=Sxy/Sxx." },
      { title: "Intercept", body: "β̂₀=ȳ−β̂₁x̄." },
      { title: "Predict", body: "ŷ=β̂₀+β̂₁x." },
    ],
    example: "ŷ = 40 + 3.5·hours → 4 hours predicts 54 points.",
    labCue: "**regression** lab — least squares line updates as you move points.",
    check: ["Does the line pass through (x̄,ȳ)?", "What is minimized?"],
    formal: "β̂ = argmin_β Σ (y_i − β₀ − β₁ x_i)².",
    formulas: "- β̂₁=Sxy/Sxx\n- β̂₀=ȳ−β̂₁x̄\n- e_i=y_i−ŷ_i",
    pitfalls: ["Extrapolating far beyond data", "Ignoring nonlinearity"],
  }),

  buildLesson({
    title: "Interpreting Regression Coefficients",
    partLabel: PART,
    principles: [
      "β₁: expected change in Y per +1 unit X (holding model)",
      "β₀: expected Y when X=0 — only meaningful if X=0 is in range",
      "Units matter",
      "Association, not automatic causation",
    ],
    objectives: [
      "Interpret slope in context with units",
      "Judge whether intercept is meaningful",
      "Avoid causal overclaim",
      "Handle scaled predictors carefully",
    ],
    why: "Stakeholders hear coefficients — wrong words create wrong decisions.",
    idea: "Slope is a rate. Intercept is a baseline sometimes fictitious.",
    steps: [
      { title: "Name variables + units", body: "Clarity." },
      { title: "Sentence for β₁", body: "'On average, +1 X associates with β₁ Y'." },
      { title: "Check x=0", body: "Is intercept substantive?" },
    ],
    example: "Score = 50 + 2.0·hours: each extra hour associates with +2 points on average.",
    labCue: "**regression** lab — change slope visually; rewrite the interpretation sentence.",
    check: ["When is β₀ nonsense?", "Does β₁ prove causality?"],
    formal: "Under causal assumptions/experimental design, β₁ can have causal reading — state them.",
    formulas: "- E[Y|X=x]=β₀+β₁x (model mean)",
    pitfalls: ["Dropping units", "Causal language from observational data"],
  }),

  buildLesson({
    title: "Coefficient of Determination",
    partLabel: PART,
    principles: [
      "R² = fraction of variance in Y explained by the model",
      "R²=1 perfect fit; R²=0 no linear explanatory power",
      "High R² ≠ correct model or causality",
      "Related to correlation: R²=r² in SLR",
    ],
    objectives: [
      "Compute R² from SST/SSR/SSE",
      "Interpret R² in words",
      "Know limitations",
      "Connect to r in simple regression",
    ],
    why: "One number summarizing fit quality — overused, still useful with caveats.",
    idea: "R² = 1 − SSE/SST = SSR/SST.",
    steps: [
      { title: "Total sum of squares", body: "SST around ȳ." },
      { title: "Error SS", body: "SSE from residuals." },
      { title: "Form R²", body: "1−SSE/SST." },
    ],
    example: "R²=0.64 ⇒ model accounts for 64% of variance in Y; r=±0.8 in SLR.",
    labCue: "**regression** lab — show R² live; add outliers and watch it move.",
    check: ["R² vs adjusted R²?", "Can R² be high with bad residuals?"],
    formal: "SST=SSR+SSE in models with intercept.",
    formulas: "- R²=1−SSE/SST\n- SLR: R²=r²",
    pitfalls: ["Maximizing R² by overfitting", "Comparing R² across different Y transformations naively"],
  }),

  buildLesson({
    title: "Inference in Regression",
    partLabel: PART,
    principles: [
      "Slope has a SE; t-tests ask if β₁=0",
      "CI for mean response vs prediction interval for a new Y",
      "Prediction intervals are wider (include irreducible error)",
      "Assumptions: linearity, independence, equal variance, normality of errors",
    ],
    objectives: [
      "Test H₀: β₁=0",
      "Distinguish confidence vs prediction intervals",
      "Interpret SE of slope",
      "State classical SLR assumptions",
    ],
    why: "Is the predictor useful? How uncertain is a forecast?",
    idea: "t = β̂₁ / SE(β̂₁). PI for new Y adds σ̂ noise beyond mean-response CI.",
    steps: [
      { title: "SE of slope", body: "From residual variance." },
      { title: "t and p-value", body: "Against β₁=0." },
      { title: "Interval type", body: "Mean vs new obs." },
    ],
    example: "β̂₁=2.0, SE=0.5 ⇒ t=4 — strong evidence of nonzero slope.",
    labCue: "**regression** lab — show band for mean CI vs wider PI.",
    check: ["Why PI wider than CI?", "df for slope t?"],
    formal: "Under Gauss–Markov + normality, β̂₁ is normal/t with known SE form.",
    formulas: "- t=β̂₁/SE(β̂₁)\n- CI mean: ŷ±t* SE(ŷ)\n- PI: ŷ±t* √(SE(ŷ)²+σ̂²)",
    pitfalls: ["Using CI when you need PI", "Ignoring assumption checks"],
  }),

  buildLesson({
    title: "Residual Analysis",
    partLabel: PART,
    principles: [
      "Residuals e=y−ŷ diagnose model problems",
      "Look for curves, fans, clumps, outliers",
      "QQ plots check normality of errors",
      "Fix: transform, add terms, robust methods",
    ],
    objectives: [
      "Plot residuals vs fitted / vs x",
      "Spot heteroscedasticity and nonlinearity",
      "Identify influential points",
      "Decide next modeling step",
    ],
    why: "A pretty R² can hide a broken model. Residuals tell the truth.",
    idea: "Random scatter around 0 is good. Patterns mean the model missed structure.",
    steps: [
      { title: "Compute residuals", body: "e_i." },
      { title: "Residual vs fitted", body: "Pattern hunt." },
      { title: "QQ plot", body: "Normality." },
      { title: "Act", body: "Transform or enrich model." },
    ],
    example: "Fan shape in residual plot ⇒ variance grows with x — consider weighted LS or transform Y.",
    labCue: "**regression** lab — residual panel updates live as you bend the truth with nonlinear points.",
    check: ["Ideal residual plot looks like?", "What is leverage?"],
    formal: "Standardized/studentized residuals; Cook's distance for influence.",
    formulas: "- e_i=y_i−ŷ_i\n- Σ e_i = 0 with intercept",
    pitfalls: ["Ignoring patterns because p-value is small", "Deleting outliers without investigation"],
  }),
];
