import { buildLesson } from "./helper.mjs";

const PART = "Part 2: Probability Theory";

export const topics = [
  buildLesson({
    title: "Basic Probability Concepts",
    partLabel: PART,
    principles: [
      "An experiment produces outcomes under uncertainty",
      "Sample space Ω lists all possible outcomes",
      "An event is a subset of Ω we care about",
      "Probability assigns weight to events — later axiomatized",
    ],
    objectives: [
      "Define experiment, outcome, sample space, event",
      "List Ω for simple chance setups",
      "Express events with set notation",
      "Connect relative frequency to probability intuition",
    ],
    why: "Every probability sentence is about an **experiment** and an **event**. Get the vocabulary right and formulas stop feeling like magic.",
    idea: "**Experiment**: procedure with uncertain result (flip a coin). **Outcome**: one result (H). **Sample space Ω**: all outcomes {H,T}. **Event**: subset, e.g. A = {H}. We ask P(A).",
    steps: [
      { title: "Name the experiment", body: "What do you repeat?" },
      { title: "List Ω", body: "Exhaustive, mutually exclusive atomic outcomes." },
      { title: "Define the event", body: "Which outcomes count as 'success' for your question?" },
      { title: "Intuition", body: "Long-run fraction of trials where the event happens." },
    ],
    example: "Roll a fair die. Ω = {1,2,3,4,5,6}. Event 'even' = {2,4,6}. Event 'at least 5' = {5,6}.",
    labCue: "Use the **sampleSpace** lab: flip coins / roll dice and highlight events as the outcome set lights up.",
    check: ["Is 'it rains tomorrow' an outcome or an event?", "Can two events share outcomes?"],
    formal: "Ω is a set; events live in a σ-algebra of subsets. Outcomes are elementary events {ω}.",
    formulas: "- Event A ⊆ Ω\n- Complement Aᶜ = Ω \\ A\n- Union / intersection: A ∪ B, A ∩ B",
    pitfalls: ["Forgetting outcomes (non-exhaustive Ω)", "Treating overlapping compound descriptions as single atoms"],
  }),

  buildLesson({
    title: "Axioms of Probability",
    partLabel: PART,
    principles: [
      "Probability is a function from events to [0,1]",
      "P(Ω) = 1; impossible event has probability 0",
      "Countable additivity for disjoint unions",
      "All rules (complements, unions) follow from axioms",
    ],
    objectives: [
      "State Kolmogorov's axioms",
      "Derive P(Aᶜ) = 1 − P(A)",
      "Use inclusion for two events",
      "Apply additivity on a partition",
    ],
    why: "Axioms are the constitution. Every later theorem (Bayes, expectation) must respect them — they keep calculations consistent.",
    idea: "(1) P(A) ≥ 0. (2) P(Ω) = 1. (3) If A_i pairwise disjoint, P(∪ A_i) = Σ P(A_i). From these: P(Aᶜ)=1−P(A), and P(A∪B)=P(A)+P(B)−P(A∩B).",
    steps: [
      { title: "Check non-negativity", body: "No negative probabilities." },
      { title: "Normalize", body: "Something in Ω must happen." },
      { title: "Add disjoint pieces", body: "Break hard events into disjoint unions." },
      { title: "Use derived rules", body: "Complements and inclusion-exclusion." },
    ],
    example: "P(rain)=0.3 ⇒ P(no rain)=0.7. If P(A)=0.4, P(B)=0.5, P(A∩B)=0.2 then P(A∪B)=0.7.",
    labCue: "In **sampleSpace**, assign weights to outcomes; watch event probabilities update from the axioms.",
    check: ["Can P(A) > 1?", "If A and B disjoint, simplify P(A∪B)."],
    formal: "Probability space (Ω, F, P) with P: F → [0,1] satisfying Kolmogorov axioms.",
    formulas: "- P(Aᶜ) = 1 − P(A)\n- P(A∪B) = P(A)+P(B)−P(A∩B)\n- If A⊆B then P(A)≤P(B)",
    pitfalls: ["Adding probabilities of overlapping events without subtracting intersection"],
  }),

  buildLesson({
    title: "Conditional Probability",
    partLabel: PART,
    principles: [
      "Conditioning updates the sample space to a known event",
      "P(A|B) = P(A∩B)/P(B) when P(B)>0",
      "Definition rearranges to the multiplication rule",
      "Almost every real inference is conditional",
    ],
    objectives: [
      "Compute P(A|B) from counts or probabilities",
      "Read two-way tables conditionally",
      "Apply the multiplication rule",
      "Avoid confusing P(A|B) with P(B|A)",
    ],
    why: "New information changes odds. Medical tests, spam filters, and debugging all ask: *given what I just saw, what's the chance now?*",
    idea: "Given B happened, restrict attention to B and ask what fraction of B also lies in A: **P(A|B) = P(A∩B)/P(B)**.",
    steps: [
      { title: "Identify given", body: "What is known? Call it B." },
      { title: "Find joint", body: "P(A∩B) or count both." },
      { title: "Divide by P(B)", body: "Normalize within the given world." },
      { title: "Sanity check", body: "Result in [0,1]; equals P(A) only if independent." },
    ],
    example: "100 students: 40 take math, 25 take both math and CS, 50 take CS. P(math|CS)=25/50=0.5. P(CS|math)=25/40=0.625 — not the same.",
    labCue: "Open the **conditional** lab: shade the two-way table; compare joint vs conditional visually.",
    check: ["Why do we need P(B)>0?", "Does P(A|B)=P(B|A) ever?"],
    formal: "For fixed B with P(B)>0, Q(A)=P(A|B) is itself a probability measure on Ω.",
    formulas: "- P(A|B)=P(A∩B)/P(B)\n- P(A∩B)=P(A|B)P(B)=P(B|A)P(A)",
    pitfalls: ["Base-rate neglect", "Swapping condition and event"],
  }),

  buildLesson({
    title: "Bayes Theorem",
    partLabel: PART,
    principles: [
      "Bayes flips P(data|hypothesis) into P(hypothesis|data)",
      "Prior × likelihood → unnormalized posterior; then normalize",
      "Total probability law expands the denominator",
      "Intuition beats memorizing the fraction alone",
    ],
    objectives: [
      "State and apply Bayes' theorem",
      "Use the law of total probability",
      "Update beliefs with a positive/negative test",
      "Explain false positives with base rates",
    ],
    why: "Spam filters, medical diagnosis, and A/B inference all invert likelihoods into beliefs about causes.",
    idea: "**P(H|D) = P(D|H)P(H) / P(D)**. Prior P(H), likelihood P(D|H), evidence P(D)=Σ P(D|H_i)P(H_i).",
    steps: [
      { title: "List hypotheses", body: "Partition of possibilities." },
      { title: "Assign priors", body: "P(H) before data." },
      { title: "Likelihoods", body: "P(data|each H)." },
      { title: "Normalize", body: "Divide by total probability of the data." },
    ],
    example: "Disease rate 1%. Test: 99% true positive, 5% false positive. Positive test → posterior ≈ 0.166, not 99%. Base rates matter.",
    labCue: "Run the **bayes** lab: slide prior and false-positive rate; watch posterior bars update.",
    check: ["What is the denominator in Bayes?", "Why can a rare disease stay unlikely after one positive test?"],
    formal: "For a partition {H_i}, P(H_k|D)=P(D|H_k)P(H_k)/Σ_j P(D|H_j)P(H_j).",
    formulas: "- Bayes: P(H|D)=P(D|H)P(H)/P(D)\n- Total prob: P(D)=Σ P(D|H_i)P(H_i)",
    pitfalls: ["Ignoring base rates", "Using P(D|H) as if it were P(H|D)"],
  }),

  buildLesson({
    title: "Independence of Events",
    partLabel: PART,
    principles: [
      "Independence means learning B does not change P(A)",
      "Equivalent: P(A∩B)=P(A)P(B)",
      "Disjoint ≠ independent (usually mutually exclusive events are dependent)",
      "Conditional independence is a different, powerful idea",
    ],
    objectives: [
      "Test independence via product rule",
      "Contrast mutually exclusive vs independent",
      "Extend to multiple events carefully",
      "Use independence to factor joint probabilities",
    ],
    why: "Independence lets you multiply probabilities — coin flips, packet losses, A/B units. Misusing it breaks models.",
    idea: "A and B are **independent** if P(A|B)=P(A) (when P(B)>0), equivalently P(A∩B)=P(A)P(B).",
    steps: [
      { title: "Compute P(A), P(B), P(A∩B)", body: "From model or data." },
      { title: "Compare product", body: "Independent iff joint equals product." },
      { title: "Interpret", body: "Does B carry information about A?" },
    ],
    example: "Two fair coins: P(H1∩H2)=1/4= (1/2)(1/2) → independent. One die: 'even' and '≤2' are not independent.",
    labCue: "In the **independence** lab, compare P(A∩B) to P(A)P(B) with live toggles.",
    check: ["Can mutually exclusive events with P>0 be independent?", "If A⊥B, is A⊥Bᶜ?"],
    formal: "Pairwise independence does not imply mutual independence for 3+ events; need all subset factorizations.",
    formulas: "- A ⊥ B ⟺ P(A∩B)=P(A)P(B)\n- Mutual: P(∩ A_i)=Π P(A_i) for all finite subcollections (full def.)",
    pitfalls: ["Assuming independence without justification", "Confusing disjoint with independent"],
  }),

  buildLesson({
    title: "Counting Principles",
    partLabel: PART,
    principles: [
      "Counting builds equally likely probability models",
      "Order matters → permutations; order doesn't → combinations",
      "Product rule multiplies sequential choices",
      "nPr and nCr are the workhorses of discrete probability",
    ],
    objectives: [
      "Apply the product and sum rules",
      "Compute permutations and combinations",
      "Choose the right tool for ordered vs unordered",
      "Solve classic urn / committee / password counts",
    ],
    why: "When outcomes are equally likely, probability = favorable / total. Counting finds both numbers.",
    idea: "**Permutation** P(n,k)=n!/(n−k)! — ordered k-selections. **Combination** C(n,k)=n!/(k!(n−k)!) — unordered teams.",
    steps: [
      { title: "Does order matter?", body: "Passwords yes; lottery tickets often no." },
      { title: "With or without replacement?", body: "Affects whether counts decrease." },
      { title: "Apply formula", body: "P or C, or product rule." },
      { title: "Divide for probability", body: "Favorable / |Ω| if uniform." },
    ],
    example: "Committee of 3 from 10: C(10,3)=120. President/VP/secretary from 10: P(10,3)=720.",
    labCue: "Use the **counting** lab: toggle permutations vs combinations and watch nPr / nCr update.",
    check: ["Why divide by k! in combinations?", "How many 4-digit PINs with repetition?"],
    formal: "Binomial theorem: (x+y)^n = Σ C(n,k) x^{n−k} y^k — combinations count subsets.",
    formulas: "- P(n,k)=n!/(n−k)!\n- C(n,k)=n!/(k!(n−k)!)\n- With replacement ordered: n^k",
    pitfalls: ["Using combinations when order matters", "Double-counting symmetries"],
  }),
];
