import { buildLesson } from "./helper.mjs";

const PART = "Part 5: Joint Distributions and Limit Theorems";

export const topics = [
  buildLesson({
    title: "Joint Probability Distributions",
    partLabel: PART,
    principles: [
      "Joint laws describe two (or more) RVs together",
      "Discrete: joint PMF p(x,y); continuous: joint PDF f(x,y)",
      "Probabilities are double sums / double integrals",
      "Independence means the joint factors",
    ],
    objectives: [
      "Read a joint PMF table",
      "Compute P((X,Y)∈A)",
      "Contrast joint vs marginal",
      "State the continuous area interpretation",
    ],
    why: "Height & weight, latency & loss, midterm & final — variables come in pairs.",
    idea: "p(x,y)=P(X=x,Y=y) or f(x,y) density on the plane. Total mass/volume = 1.",
    steps: [
      { title: "Write support", body: "Possible (x,y) pairs." },
      { title: "Assign joint weights", body: "Table or formula." },
      { title: "Sum/integrate region", body: "Event of interest." },
    ],
    example: "Two coin flips: joint of (X=#heads first, Y=#heads second) on {0,1}² with equal 1/4.",
    labCue: "**joint** lab — heatmap of joint mass; hover cells for p(x,y).",
    check: ["Must joint PMF sum to 1?", "Can continuous joint give P(exact point)?"],
    formal: "F_{X,Y}(x,y)=P(X≤x,Y≤y).",
    formulas: "- ΣΣ p(x,y)=1\n- ∫∫ f=1\n- P(A)=ΣΣ_{(x,y)∈A} p",
    pitfalls: ["Treating marginals as if they determine the joint (they don't)"],
  }),

  buildLesson({
    title: "Marginal and Conditional Distributions",
    partLabel: PART,
    principles: [
      "Marginals collapse the joint by summing/integrating out the other variable",
      "Conditionals renormalize a slice of the joint",
      "p(x|y)=p(x,y)/p_Y(y)",
      "Recovery: joint = conditional × marginal",
    ],
    objectives: [
      "Compute marginal PMFs/PDFs",
      "Form conditional distributions",
      "Reconstruct joints when given conditional+marginal",
      "Interpret slices of a heatmap",
    ],
    why: "You often observe one variable and need the law of the other — that's conditional.",
    idea: "Sum across a row/column for marginals. Divide the joint row by its marginal to get conditional.",
    steps: [
      { title: "Marginalize", body: "Sum/integrate the nuisance variable." },
      { title: "Pick the given value", body: "Fix Y=y." },
      { title: "Renormalize", body: "Divide joint by p_Y(y)." },
    ],
    example: "From a 2×2 joint table, P(X=1|Y=0)=p(1,0)/P(Y=0).",
    labCue: "**joint** lab — show marginal bars; click a row to see conditional.",
    check: ["Can identical marginals hide dependence?", "Formula for p(x|y)?"],
    formal: "f(x|y)=f(x,y)/f_Y(y) when f_Y(y)>0.",
    formulas: "- p_X(x)=Σ_y p(x,y)\n- p(x|y)=p(x,y)/p_Y(y)",
    pitfalls: ["Forgetting to renormalize", "Confusing p(x|y) with p(y|x)"],
  }),

  buildLesson({
    title: "Covariance and Correlation",
    partLabel: PART,
    principles: [
      "Covariance tracks how X and Y move together",
      "Correlation scales cov to [-1,1]",
      "Corr=0 means uncorrelated, not always independent",
      "Linear association ≠ causation",
    ],
    objectives: [
      "Compute Cov(X,Y)=E[(X−μx)(Y−μy)]",
      "Convert to correlation ρ",
      "Interpret sign and magnitude of ρ",
      "Know limitations (nonlinear dependence)",
    ],
    why: "Risk, diversification, feature relationships — association strength in one number.",
    idea: "Positive cov: above-mean X tends to meet above-mean Y. ρ = cov/(σx σy).",
    steps: [
      { title: "Center variables", body: "Subtract means." },
      { title: "Average products", body: "That's covariance." },
      { title: "Scale by SDs", body: "Correlation." },
    ],
    example: "Study hours and exam scores often ρ>0. Perfect line ⇒ |ρ|=1.",
    labCue: "**joint**/scatter in regression lab — watch ρ change as you drag cloud shape.",
    check: ["Can dependent variables have ρ=0?", "Units of cov vs corr?"],
    formal: "Cov(X,Y)=E[XY]−μxμy. |ρ|≤1 by Cauchy–Schwarz.",
    formulas: "- Cov=E[(X−μx)(Y−μy)]\n- ρ=Cov/(σxσy)",
    pitfalls: ["Equating corr=0 with independence", "Trusting ρ for curved relationships"],
  }),

  buildLesson({
    title: "Independence of Random Variables",
    partLabel: PART,
    principles: [
      "X⊥Y iff joint = product of marginals",
      "Independence ⇒ uncorrelated, converse false in general",
      "Functions of independent RVs stay independent",
      "Critical modeling assumption — validate when possible",
    ],
    objectives: [
      "Test factorization of joints",
      "Use independence to multiply probabilities",
      "Give a counterexample: uncorrelated but dependent",
      "Factor expectations of products when independent",
    ],
    why: "i.i.d. samples power LLN, CLT, and most textbook inference.",
    idea: "Knowing Y tells nothing about X. Check p(x,y)=p_X(x)p_Y(y) for all x,y.",
    steps: [
      { title: "Get joint and marginals", body: "From model or table." },
      { title: "Compare to product", body: "Any mismatch ⇒ dependence." },
      { title: "Use consequences", body: "E[XY]=E[X]E[Y], Var additivity." },
    ],
    example: "Let Z~N(0,1), X=Z, Y=Z². Corr may be 0 but Y is determined by |related to| X — dependent.",
    labCue: "**joint** lab — switch between independent product joints and coupled joints.",
    check: ["Does uncorrelated imply independent for jointly normal?", "Why i.i.d. matters for CLT?"],
    formal: "For jointly continuous: f(x,y)=f_X(x)f_Y(y) a.e.",
    formulas: "- X⊥Y ⇒ P(X∈A,Y∈B)=P(X∈A)P(Y∈B)\n- ⇒ E[g(X)h(Y)]=E[g]E[h]",
    pitfalls: ["Assuming independence of time series residuals blindly"],
  }),

  buildLesson({
    title: "Linear Combinations of Random Variables",
    partLabel: PART,
    principles: [
      "Means: E[aX+bY]=aE[X]+bE[Y] always",
      "Variances need covariances when dependent",
      "Normal linear combos stay normal if jointly normal",
      "Standardization is a linear combo",
    ],
    objectives: [
      "Compute mean of aX+bY",
      "Expand Var(aX+bY)",
      "Handle sums of i.i.d. variables",
      "Prepare for sampling distribution of x̄",
    ],
    why: "Sample means, portfolio returns, difference of estimators — all linear combos.",
    idea: "Var(aX+bY)=a²Var(X)+b²Var(Y)+2ab Cov(X,Y).",
    steps: [
      { title: "Mean first", body: "Linearity." },
      { title: "Expand variance", body: "Include cross term." },
      { title: "Simplify if independent", body: "Drop covariance." },
    ],
    example: "i.i.d. Var(X_i)=σ² ⇒ Var(X̄)=σ²/n.",
    labCue: "Expectation lab / CLT lab — average of draws; variance shrinks like 1/n.",
    check: ["Var(X+X)?", "Var(X−Y) if independent equal var?"],
    formal: "Affine transforms of multivariate normals remain normal.",
    formulas: "- E[Σ a_i X_i]=Σ a_i E[X_i]\n- Var(X̄)=σ²/n (i.i.d.)",
    pitfalls: ["Forgetting 2abCov", "Dividing SD by n instead of √n"],
  }),

  buildLesson({
    title: "Law of Large Numbers",
    partLabel: PART,
    principles: [
      "Sample averages converge to the expectation",
      "More data → less sampling noise around μ",
      "Requires finite mean (and i.i.d. in basic form)",
      "Does not say every sequence looks typical early on",
    ],
    objectives: [
      "State LLN in plain language",
      "Distinguish LLN from CLT",
      "Simulate running means converging",
      "Avoid gambler's fallacy misreadings",
    ],
    why: "Why polls need large n; why casinos win long-term; why x̄ estimates μ.",
    idea: "For i.i.d. with E[X_i]=μ, X̄_n → μ as n→∞ (in probability / a.s. under conditions).",
    steps: [
      { title: "Assume i.i.d. + finite mean", body: "Setup." },
      { title: "Form X̄_n", body: "Average of first n draws." },
      { title: "Increase n", body: "Watch convergence." },
    ],
    example: "Fair die: running mean of faces → 3.5 after many rolls.",
    labCue: "**lln** lab — stream random trials; plot running mean vs μ.",
    check: ["Does LLN give a normal shape?", "What if variance infinite?"],
    formal: "WLLN: X̄ →_P μ. SLLN: almost sure convergence under stronger hypotheses.",
    formulas: "- X̄_n=(X_1+…+X_n)/n → μ",
    pitfalls: ["Thinking short streaks must 'correct' immediately", "Confusing LLN with CLT"],
  }),

  buildLesson({
    title: "Central Limit Theorem",
    partLabel: PART,
    principles: [
      "Sums/averages become approximately normal for large n",
      "Works for many non-normal i.i.d. populations with finite variance",
      "Standardize: √n (X̄−μ)/σ → N(0,1)",
      "Quality of approx depends on n and skewness",
    ],
    objectives: [
      "State CLT for sample means",
      "Compute approximate probabilities for X̄",
      "Choose when n is 'large enough' qualitatively",
      "Contrast with exact normal sampling for normal data",
    ],
    why: "The theorem that makes z-tests and many CIs possible without knowing the full population shape.",
    idea: "Average many independent noisy pieces → bell curve. Speed of approach worsens with skew.",
    steps: [
      { title: "Identify μ,σ,n", body: "Population moments." },
      { title: "Treat X̄ ≈ N(μ, σ²/n)", body: "CLT approximation." },
      { title: "Standardize", body: "Use Φ." },
    ],
    example: "Fair coin, n=100, X̄=proportion heads ≈ N(0.5, 0.25/100). P(X̄>0.6) via z.",
    labCue: "**clt** lab — histogram of many sample means; increase n; watch normality.",
    check: ["Does CLT need normal population?", "SE of mean formula?"],
    formal: "√n (X̄−μ)/σ ⇒ N(0,1) in distribution as n→∞.",
    formulas: "- X̄ ≈ N(μ, σ²/n)\n- z=√n (x̄−μ)/σ",
    pitfalls: ["Using CLT for tiny n with skewed data", "Using σ/n not σ/√n"],
  }),
];
