import { buildLesson } from "./helper.mjs";

const PART = "Part 3: Random Variables and Distributions";

export const topics = [
  buildLesson({
    title: "Discrete Random Variables and PMFs",
    partLabel: PART,
    principles: [
      "A random variable maps outcomes to numbers",
      "Discrete RVs take countable values",
      "The PMF p(x)=P(X=x) fully describes a discrete law",
      "PMFs are non-negative and sum to 1",
    ],
    objectives: [
      "Define a discrete random variable",
      "Write and validate a PMF",
      "Compute event probabilities by summing PMF values",
      "Graph a PMF as a stem plot",
    ],
    why: "Events become numeric: X = number of bugs, packet losses, correct quiz answers. The PMF is the discrete distribution.",
    idea: "**X: Ω → ℝ**. If X takes values in a countable set, it is discrete. **PMF**: p(x)=P(X=x). Then P(X∈A)=Σ_{x∈A} p(x).",
    steps: [
      { title: "Define X in words", body: "What number do you extract from each outcome?" },
      { title: "List support", body: "Possible values of X." },
      { title: "Assign p(x)", body: "Non-negative, sum to 1." },
      { title: "Answer questions", body: "Sum over the relevant values." },
    ],
    example: "Fair die: X=face. p(x)=1/6 for x=1..6. P(X≥5)=p(5)+p(6)=1/3.",
    labCue: "Use the **pmf** lab: adjust a discrete distribution and watch stems resize while the sum stays 1.",
    check: ["Can a PMF be greater than 1 at a point?", "How do you get P(X≤k)?"],
    formal: "p_X(x)=P(X=x). CDF F(x)=Σ_{t≤x} p(t).",
    formulas: "- Σ_x p(x)=1\n- P(a≤X≤b)=Σ_{x=a}^b p(x) for integer support",
    pitfalls: ["Forgetting to check Σ p=1", "Treating continuous densities as point masses"],
  }),

  buildLesson({
    title: "Continuous Random Variables and PDFs",
    partLabel: PART,
    principles: [
      "Continuous RVs have P(X=x)=0 for each single x",
      "Probability lives in areas under the PDF",
      "PDF f satisfies f≥0 and ∫ f = 1",
      "P(a<X<b)=∫_a^b f(x) dx",
    ],
    objectives: [
      "Contrast PDF with PMF",
      "Compute probabilities as integrals / areas",
      "Interpret f(x) as relative likelihood, not a probability",
      "Connect histograms to density estimates",
    ],
    why: "Time, measurement noise, and many physical quantities are continuous. Densities replace point masses.",
    idea: "A **PDF** f is a curve; probability is **area**. Height f(x) is not P(X=x).",
    steps: [
      { title: "Identify support", body: "Where f>0." },
      { title: "Normalize", body: "Ensure total area is 1." },
      { title: "Integrate", body: "Area between bounds = probability." },
      { title: "Visualize", body: "Shade the region of interest." },
    ],
    example: "Uniform(0,1): f(x)=1 on (0,1). P(0.2<X<0.5)=0.3. P(X=0.3)=0.",
    labCue: "Open the **pdf** lab: shade an interval under the curve; read the area as probability.",
    check: ["Why is P(X=x)=0?", "Can f(x)>1?"],
    formal: "F(x)=∫_{-∞}^x f; f=F' where differentiable. Absolute continuity required for a PDF representation.",
    formulas: "- ∫_{-∞}^{∞} f(x)dx=1\n- P(a<X<b)=∫_a^b f",
    pitfalls: ["Reading f(x) as a probability", "Forgetting units of density (1/unit of x)"],
  }),

  buildLesson({
    title: "Cumulative Distribution Functions",
    partLabel: PART,
    principles: [
      "The CDF F(x)=P(X≤x) works for discrete and continuous",
      "F is nondecreasing, right-continuous, limits 0 and 1",
      "PDF is derivative of CDF; PMF is jump sizes of CDF",
      "Tail probabilities use 1−F",
    ],
    objectives: [
      "Define and sketch a CDF",
      "Recover PMF jumps or PDF slopes from F",
      "Compute intervals via F(b)−F(a)",
      "Use CDFs for quantiles",
    ],
    why: "One function unifies discrete and continuous. Software, tables, and theory all speak CDF.",
    idea: "**F(x)=P(X≤x)**. Continuous: smooth rise. Discrete: staircase. P(a<X≤b)=F(b)−F(a) (careful with equality at atoms).",
    steps: [
      { title: "Accumulate", body: "From −∞ up to x, add all probability mass/area." },
      { title: "Read probabilities", body: "Differences of F." },
      { title: "Invert for quantiles", body: "Find smallest x with F(x)≥p." },
    ],
    example: "Exponential waiting time: F(t)=1−e^{−λt} for t≥0. Median solves F(m)=0.5 ⇒ m=ln2/λ.",
    labCue: "Use the **cdf** lab: toggle PDF↔CDF and watch them stay consistent.",
    check: ["What is lim x→∞ F(x)?", "How does a point mass appear in F?"],
    formal: "Any RV has a CDF. Distribution uniquely determined by F.",
    formulas: "- F(x)=P(X≤x)\n- Continuous: f=F'\n- Quantile: F^{-1}(p)=inf{x: F(x)≥p}",
    pitfalls: ["Using F(b)−F(a) incorrectly around discrete atoms", "Confusing < vs ≤"],
  }),

  buildLesson({
    title: "Expected Value and Variance",
    partLabel: PART,
    principles: [
      "Expectation is a probability-weighted average",
      "Variance measures spread around the mean",
      "E[X] exists only if the absolute series/integral converges",
      "SD = √Var is the interpretable scale",
    ],
    objectives: [
      "Compute E[X] for discrete and continuous RVs",
      "Compute Var(X)=E[(X−μ)²]=E[X²]−μ²",
      "Interpret mean as long-run average of i.i.d. samples",
      "Relate to sample mean and sample variance",
    ],
    why: "Prediction and risk live here: expected reward, expected error, volatility.",
    idea: "Discrete: E[X]=Σ x p(x). Continuous: E[X]=∫ x f(x)dx. Variance = expected squared deviation from μ.",
    steps: [
      { title: "Get the distribution", body: "PMF or PDF." },
      { title: "Mean", body: "Weighted average of x." },
      { title: "Second moment", body: "E[X²] then Var=E[X²]−μ²." },
      { title: "SD", body: "Square root." },
    ],
    example: "Fair die: E[X]=3.5, E[X²]=91/6, Var=35/12 ≈ 2.92, SD≈1.71.",
    labCue: "The **expectation** lab balances a seesaw of masses (PMF stems) — fulcrum at E[X].",
    check: ["Can E[X] fail to exist?", "Is Var always ≥ 0?"],
    formal: "For g(X), E[g(X)]=Σ g(x)p(x) or ∫ g f (law of the unconscious statistician).",
    formulas: "- μ=E[X]\n- Var(X)=E[X²]−μ²\n- SD=√Var",
    pitfalls: ["Averaging x without weights", "Confusing E[X²] with (E[X])²"],
  }),

  buildLesson({
    title: "Properties of Expectation and Variance",
    partLabel: PART,
    principles: [
      "Expectation is linear even without independence",
      "Var(aX+b)=a²Var(X)",
      "For independent X,Y: Var(X+Y)=Var(X)+Var(Y)",
      "Covariance appears when dependence matters",
    ],
    objectives: [
      "Use linearity E[aX+bY]=aE[X]+bE[Y]",
      "Scale variances correctly",
      "Add variances only under independence (or zero cov)",
      "Bound mistakes like Var(X+Y)=Var(X)+Var(Y) always",
    ],
    why: "Almost every derivation (CLT standardization, regression, portfolio risk) uses these algebra rules.",
    idea: "Means add for any RVs. Variances add for **independent** RVs; otherwise include 2Cov.",
    steps: [
      { title: "Linearity", body: "Pull out constants; split sums." },
      { title: "Shift", body: "Adding b does not change variance." },
      { title: "Scale", body: "Multiply RV by a → multiply Var by a²." },
      { title: "Independence check", body: "Before adding Vars." },
    ],
    example: "X,Y i.i.d. with Var=4. Var(3X−2)=9·4=36. Var(X+Y)=8. Var(X−Y)=8.",
    labCue: "In **expectation**, scale and shift the distribution; confirm μ and σ² transform as predicted.",
    check: ["Does E[XY]=E[X]E[Y] always?", "What is Var(X+X)?"],
    formal: "Var(X+Y)=Var(X)+Var(Y)+2Cov(X,Y). Cov=0 if uncorrelated (weaker than independent).",
    formulas: "- E[aX+b]=aE[X]+b\n- Var(aX+b)=a²Var(X)\n- Independent ⇒ Var(Σ X_i)=Σ Var(X_i)",
    pitfalls: ["Adding SDs instead of variances", "Assuming uncorrelated ⇒ independent"],
  }),
];
