import { buildLesson } from "./helper.mjs";

const PART = "Part 6: Sampling and Estimation";

export const topics = [
  buildLesson({
    title: "Populations and Samples",
    partLabel: PART,
    principles: [
      "Population = full set of interest; sample = observed subset",
      "Parameters describe populations; statistics describe samples",
      "Random sampling justifies probability models for statistics",
      "Bias starts with how you sample, not only with formulas",
    ],
    objectives: [
      "Define population, sample, parameter, statistic",
      "Give examples of biased sampling",
      "Explain why randomness matters",
      "Preview inference goal: learn parameters from statistics",
    ],
    why: "You almost never see the whole population. Inference is disciplined guessing from samples.",
    idea: "μ,σ,p are **parameters**. x̄,s,p̂ are **statistics** — random before you look at data.",
    steps: [
      { title: "Name the population", body: "Who/what in scope?" },
      { title: "Describe sampling plan", body: "SRS? stratified? convenience?" },
      { title: "Identify parameter vs statistic", body: "Target vs estimator." },
    ],
    example: "All MUST CS students = population; 80 surveyed GPAs = sample; mean GPA μ vs sample mean x̄.",
    labCue: "**sampling** lab — draw random subsets from a finite population urn; compare sample mean to μ.",
    check: ["Is x̄ a parameter?", "Why is convenience sampling dangerous?"],
    formal: "A sample X_1..X_n is modeled as RVs; a statistic is a function T(X_1..X_n).",
    formulas: "- Parameter θ ∈ population\n- Estimator θ̂ = T(sample)",
    pitfalls: ["Volunteer bias", "Survivorship bias", "Confusing census with sample"],
  }),

  buildLesson({
    title: "Sampling Distributions",
    partLabel: PART,
    principles: [
      "A statistic has its own distribution across repeated samples",
      "Sampling distribution of x̄ centers at μ with SE σ/√n",
      "Proportion p̂ has mean p and variance p(1−p)/n",
      "CLT approximates many sampling distributions",
    ],
    objectives: [
      "Define sampling distribution",
      "State mean/SE of x̄ and p̂",
      "Simulate repeated samples mentally and in lab",
      "Connect SE to precision",
    ],
    why: "Inference uncertainty comes from the sampling distribution — not from one lucky sample.",
    idea: "Imagine redrawing the sample forever; histogram of x̄ values is the sampling distribution.",
    steps: [
      { title: "Fix population & n", body: "Setup." },
      { title: "Compute statistic each draw", body: "x̄ or p̂." },
      { title: "Describe spread", body: "SE formulas." },
    ],
    example: "σ=10, n=25 ⇒ SE(x̄)=2. Larger n → tighter sampling distribution.",
    labCue: "**sampling** lab — animate many samples; histogram of means.",
    check: ["SE vs SD of one observation?", "Effect of 4×n on SE?"],
    formal: "Law of x̄ under i.i.d.: E[x̄]=μ, Var=σ²/n.",
    formulas: "- SE(x̄)=σ/√n\n- SE(p̂)=√(p(1−p)/n)",
    pitfalls: ["Using σ instead of σ/√n for means", "Ignoring dependence in samples"],
  }),

  buildLesson({
    title: "Point Estimation",
    partLabel: PART,
    principles: [
      "A point estimator gives a single best guess of θ",
      "Unbiased: E[θ̂]=θ",
      "Consistency: θ̂→θ as n→∞",
      "Efficiency compares variances among unbiased estimators",
    ],
    objectives: [
      "Define bias and MSE",
      "Check unbiasedness for x̄ and p̂",
      "Explain consistency via LLN",
      "Trade bias vs variance qualitatively",
    ],
    why: "Every dashboard metric is an estimator. Good ones are accurate (low bias) and precise (low variance).",
    idea: "Bias = E[θ̂]−θ. MSE = Var(θ̂)+bias². Unbiased + vanishing variance ⇒ consistent.",
    steps: [
      { title: "Propose θ̂", body: "Formula in sample." },
      { title: "Compute E[θ̂]", body: "Bias?" },
      { title: "Study Var/MSE", body: "Precision." },
    ],
    example: "For i.i.d. mean μ, x̄ is unbiased and consistent. Sample variance with /n is slightly biased; /(n−1) unbiased.",
    labCue: "**estimation** lab — compare biased vs unbiased variance estimators across trials.",
    check: ["Can a biased estimator be useful?", "MSE formula?"],
    formal: "MSE(θ̂)=E[(θ̂−θ)²]=Var(θ̂)+(Bias)².",
    formulas: "- Bias=E[θ̂]−θ\n- x̄ unbiased for μ\n- p̂ unbiased for p",
    pitfalls: ["Equating unbiased with 'always correct'", "Ignoring MSE"],
  }),

  buildLesson({
    title: "Method of Moments",
    partLabel: PART,
    principles: [
      "Equate sample moments to population moments",
      "Solve for unknown parameters",
      "Simple and general, not always efficient",
      "First moment often recovers means; higher moments for more params",
    ],
    objectives: [
      "Form moment equations",
      "Estimate parameters for common families",
      "Contrast MOM with MLE briefly",
      "Check estimates land in valid parameter space",
    ],
    why: "Quick closed-form estimators when likelihoods are messy.",
    idea: "Set x̄ = E[X|θ] (and higher moments if needed); solve for θ.",
    steps: [
      { title: "Write population moments", body: "In terms of θ." },
      { title: "Replace with sample moments", body: "x̄, m₂, …" },
      { title: "Solve", body: "θ̂_MOM." },
    ],
    example: "Exp(λ): E[X]=1/λ ⇒ λ̂=1/x̄.",
    labCue: "**estimation** lab — MOM fit for exponential draws.",
    check: ["One parameter ⇒ how many moment equations?", "MOM always = MLE?"],
    formal: "k parameters ↔ first k moment conditions.",
    formulas: "- μ₁(θ)=E[X], set = x̄\n- For two params, also match second moment",
    pitfalls: ["MOM estimates outside parameter space", "Poor efficiency vs MLE in some models"],
  }),

  buildLesson({
    title: "Maximum Likelihood Estimation",
    partLabel: PART,
    principles: [
      "Likelihood = probability/density of data as a function of θ",
      "MLE maximizes likelihood (or log-likelihood)",
      "Often found by derivative = 0 or by numerics",
      "Asymptotically efficient under regularity",
    ],
    objectives: [
      "Write a likelihood for i.i.d. data",
      "Maximize log L for Bernoulli/normal mean",
      "Interpret MLE as 'most compatible θ'",
      "Compare to MOM on examples",
    ],
    why: "Default modern estimator — logistic regression, Gaussians, almost every ML loss has an MLE cousin.",
    idea: "Pick θ that makes the observed sample most probable. Maximize Π f(x_i|θ).",
    steps: [
      { title: "Write L(θ)", body: "Product of densities/PMFs." },
      { title: "Take log", body: "Sum is easier." },
      { title: "Differentiate / argue", body: "Critical point or boundary." },
      { title: "Verify maximum", body: "Second derivative or logic." },
    ],
    example: "i.i.d. Bern(p): p̂_MLE = x̄ (sample proportion).",
    labCue: "**estimation** lab — plot log-likelihood curve; mark the maximizing p.",
    check: ["Why log?", "MLE invariant under reparameterization?"],
    formal: "θ̂_MLE = argmax_θ L(θ; data).",
    formulas: "- ℓ(θ)=Σ log f(x_i|θ)\n- Bernoulli: p̂=x̄\n- Normal mean (σ known): μ̂=x̄",
    pitfalls: ["Multiple local maxima", "Flat likelihoods / non-identifiability"],
  }),

  buildLesson({
    title: "Confidence Intervals for Means",
    partLabel: PART,
    principles: [
      "A CI is a random interval that covers θ with stated long-run frequency",
      "Known σ: z-interval; unknown σ: t-interval",
      "Width shrinks like 1/√n",
      "Confidence level ≠ P(θ in this fixed interval) after seeing data (frequentist reading)",
    ],
    objectives: [
      "Build z and t CIs for μ",
      "Choose z vs t",
      "Interpret confidence level via capture rate",
      "Relate SE and critical values to width",
    ],
    why: "Point estimates need uncertainty. CIs communicate precision to readers and product stakeholders.",
    idea: "x̄ ± z_{α/2}·σ/√n (σ known) or × s/√n with t_{n−1} critical value.",
    steps: [
      { title: "Check assumptions", body: "Approx normal / large n / SRS." },
      { title: "Compute SE", body: "σ/√n or s/√n." },
      { title: "Critical value", body: "z or t." },
      { title: "Form interval", body: "center ± margin." },
    ],
    example: "n=36, x̄=80, σ=12, 95%: 80±1.96·2 → (76.08, 83.92).",
    labCue: "**confidence** lab — many samples; draw intervals; count how often they cover μ.",
    check: ["Does 95% CI mean θ is random?", "Effect of larger n?"],
    formal: "P(θ ∈ [L,U]) = 1−α where randomness is in L,U.",
    formulas: "- z-CI: x̄±z_{α/2} σ/√n\n- t-CI: x̄±t_{n−1,α/2} s/√n",
    pitfalls: ["Using z with tiny n and unknown σ", "Misinterpreting confidence as posterior probability"],
  }),

  buildLesson({
    title: "Confidence Intervals for Proportions",
    partLabel: PART,
    principles: [
      "p̂ estimates Bernoulli/Binomial proportion p",
      "Wald interval uses SE √(p̂(1−p̂)/n)",
      "Need np̂ and n(1−p̂) large enough for normal approx",
      "Agresti–Coull / Wilson improve small-sample behavior",
    ],
    objectives: [
      "Construct a large-sample CI for p",
      "Check success-failure conditions",
      "Interpret margins of error in polls",
      "Know when to prefer adjusted intervals",
    ],
    why: "Click rates, defect rates, vote shares — proportion CIs are everywhere in product analytics.",
    idea: "p̂ ± z √(p̂(1−p̂)/n) when n is large enough.",
    steps: [
      { title: "Compute p̂", body: "successes/n." },
      { title: "Check np̂, n(1−p̂)", body: "Often ≥10 rule of thumb." },
      { title: "Margin of error", body: "z·SE." },
    ],
    example: "12 conversions / 200 visits: p̂=0.06. Check conditions; build 95% Wald CI carefully (borderline).",
    labCue: "**confidence** lab — proportion mode; capture rate of p.",
    check: ["SE of p̂ formula?", "Why fail near p=0 or 1 with small n?"],
    formal: "By CLT, √n (p̂−p)/√(p(1−p)) → N(0,1).",
    formulas: "- SE≈√(p̂(1−p̂)/n)\n- CI: p̂±z_{α/2} SE",
    pitfalls: ["Wald intervals with 0 successes", "Treating MOE as valid for subgroups automatically"],
  }),
];
