import { buildLesson } from "./helper.mjs";

const PART = "Part 7: Hypothesis Testing";

export const topics = [
  buildLesson({
    title: "Null and Alternative Hypotheses",
    partLabel: PART,
    principles: [
      "H₀ is the skeptical default; H₁ is the claim needing evidence",
      "Tests ask if data are surprising under H₀",
      "One-sided vs two-sided alternatives change rejection regions",
      "Failing to reject ≠ proving H₀ true",
    ],
    objectives: [
      "Write H₀ and H₁ for means and proportions",
      "Choose one-sided vs two-sided",
      "Explain the logic of proof by contradiction",
      "Avoid accepting H₀ language",
    ],
    why: "A/B tests, drug trials, quality control — formal decisions under uncertainty.",
    idea: "Assume H₀, measure how weird the data look, reject H₀ only if weirdness exceeds a threshold.",
    steps: [
      { title: "State parameter", body: "μ, p, difference, …" },
      { title: "Write H₀", body: "Usually equality." },
      { title: "Write H₁", body: ">, <, or ≠." },
    ],
    example: "H₀: p=0.5 fair coin vs H₁: p≠0.5. Data with 80 heads / 100 tosses look extreme under H₀.",
    labCue: "**hypothesis** lab — set H₀ mean; see where sample mean falls under the null curve.",
    check: ["Why put equality in H₀?", "What does 'fail to reject' mean?"],
    formal: "Test is a partition of sample space into reject / retain regions for H₀.",
    formulas: "- H₀: θ=θ₀\n- H₁: θ>θ₀ or θ<θ₀ or θ≠θ₀",
    pitfalls: ["Reversing H₀/H₁ for convenience", "Claiming H₀ proven"],
  }),

  buildLesson({
    title: "Type I and Type II Errors",
    partLabel: PART,
    principles: [
      "Type I: reject true H₀ (false positive)",
      "Type II: miss false H₀ (false negative)",
      "Significance level α = P(Type I) under H₀",
      "Power = 1 − β = P(reject | H₁ true)",
    ],
    objectives: [
      "Define α, β, power",
      "Trade off Type I vs Type II",
      "See how n and effect size change power",
      "Pick α consciously (0.05 is convention, not magic)",
    ],
    why: "Shipping a bad feature (Type I) vs missing a real win (Type II) — product costs differ.",
    idea: "α controls false alarms; more power needs larger n, larger effects, or higher α.",
    steps: [
      { title: "Fix α", body: "Rejection threshold under H₀." },
      { title: "Imagine H₁ true", body: "Distribution shifts." },
      { title: "Power", body: "Area of rejection under H₁." },
    ],
    example: "Stricter α=0.01 reduces false discoveries but can miss real A/B lifts (lower power).",
    labCue: "**hypothesis** lab — shade Type I region; shift mean for Type II/power.",
    check: ["Power vs α relationship?", "Effect of larger n on β?"],
    formal: "β(θ)=P(retain H₀ | θ) for θ in H₁; power=1−β(θ).",
    formulas: "- α=P(reject|H₀)\n- β=P(retain|H₁)\n- Power=1−β",
    pitfalls: ["Ignoring power when n is tiny", "p-hacking to 'get significance'"],
  }),

  buildLesson({
    title: "Z-Tests and T-Tests",
    partLabel: PART,
    principles: [
      "z-test when σ known or n large; t when σ unknown and normal-ish",
      "Test statistic measures SE-scaled distance from H₀",
      "p-value = tail probability under H₀",
      "One-sample and two-sample variants",
    ],
    objectives: [
      "Compute z and t statistics",
      "Find p-values / critical values",
      "Run one-sample and two-sample tests",
      "State assumptions",
    ],
    why: "Default toolkit comparing a mean to a target or two groups' means.",
    idea: "z=(x̄−μ₀)/(σ/√n). Replace σ with s and use t_{n−1} when σ unknown.",
    steps: [
      { title: "Hypotheses", body: "H₀/H₁." },
      { title: "Statistic", body: "z or t." },
      { title: "p-value", body: "Compare to α." },
      { title: "Conclude", body: "Reject or not + context." },
    ],
    example: "H₀: μ=100, n=25, x̄=104, s=8 ⇒ t=2.5; two-sided p≈0.02 — reject at 5%.",
    labCue: "**hypothesis** lab — t/z slider; mark observed statistic and p-value.",
    check: ["When prefer t over z?", "Two-sample pooled vs unpooled?"],
    formal: "Under H₀ and normality, t = (x̄−μ₀)/(s/√n) ~ t_{n−1}.",
    formulas: "- z=(x̄−μ₀)/(σ/√n)\n- t=(x̄−μ₀)/(s/√n)\n- two-sample: (x̄₁−x̄₂)/SE_diff",
    pitfalls: ["Using z with tiny n unknown σ", "Omitting assumptions"],
  }),

  buildLesson({
    title: "Paired T-Tests",
    partLabel: PART,
    principles: [
      "Paired data: two measurements on the same unit",
      "Analyze differences D_i = X_i − Y_i",
      "Reduces subject-to-subject noise",
      "Assumptions apply to differences",
    ],
    objectives: [
      "Recognize paired designs",
      "Run one-sample t on differences",
      "Contrast with independent two-sample t",
      "Interpret before/after studies",
    ],
    why: "Pre/post training scores, two algorithms on the same inputs — pairing is power.",
    idea: "H₀: μ_D=0. Use t based on d̄ and s_D.",
    steps: [
      { title: "Form differences", body: "One per pair." },
      { title: "One-sample t", body: "On D_i." },
      { title: "Conclude on mean change", body: "Sign matters." },
    ],
    example: "10 students: after−before coding speed. Positive d̄ with small s_D ⇒ significant improvement.",
    labCue: "**hypothesis** lab — paired mode; correlated before/after reduces SE of differences.",
    check: ["Why not ignore pairing?", "df for paired t?"],
    formal: "If D_i i.i.d. normal, t=d̄/(s_D/√n)~t_{n−1} under μ_D=0.",
    formulas: "- D_i=X_i−Y_i\n- t=d̄/(s_D/√n)",
    pitfalls: ["Using two-sample t on paired data", "Pairing unmatched units"],
  }),

  buildLesson({
    title: "Chi-Square Goodness of Fit",
    partLabel: PART,
    principles: [
      "Compares observed counts to expected counts under a model",
      "Statistic Σ (O−E)²/E ~ χ² approx",
      "df = categories − 1 − estimated params",
      "Needs adequate expected counts",
    ],
    objectives: [
      "Compute expected counts",
      "Calculate χ² statistic",
      "Choose df correctly",
      "Test fairness of a die / distribution fit",
    ],
    why: "Is this die fair? Does traffic match a claimed distribution?",
    idea: "Large mismatches between O and E inflate χ² → reject the claimed probabilities.",
    steps: [
      { title: "State claimed p_i", body: "H₀." },
      { title: "E_i=n p_i", body: "Expected counts." },
      { title: "Sum (O−E)²/E", body: "Statistic." },
      { title: "χ² tail p-value", body: "df=k−1." },
    ],
    example: "60 die rolls; E_i=10 each face; compute χ² vs χ²_5 critical value.",
    labCue: "**hypothesis** lab — categorical counts; animated χ² contribution bars.",
    check: ["Rule of thumb for E_i?", "df if probabilities fully specified?"],
    formal: "Pearson statistic → χ²_{k−1} under H₀ as n→∞.",
    formulas: "- χ²=Σ (O_i−E_i)²/E_i\n- E_i=n p_i",
    pitfalls: ["Tiny expected counts", "Wrong df when parameters estimated"],
  }),

  buildLesson({
    title: "Chi-Square Test for Independence",
    partLabel: PART,
    principles: [
      "Two-way tables: test association between categorical variables",
      "Expected counts from row/column totals under independence",
      "Same χ² form Σ(O−E)²/E",
      "df=(r−1)(c−1)",
    ],
    objectives: [
      "Build expected table under independence",
      "Run χ² independence test",
      "Interpret association vs causation",
      "Know residuals for which cells drive significance",
    ],
    why: "Do major and internship status associate? UX: device vs conversion?",
    idea: "If independent, E_{ij}= (row i total)(col j total)/n. Big deviations ⇒ dependence.",
    steps: [
      { title: "Margins", body: "Row and column totals." },
      { title: "Expected grid", body: "Products / n." },
      { title: "χ² and df", body: "(r−1)(c−1)." },
    ],
    example: "2×2 smoking vs disease table — classic independence test.",
    labCue: "**hypothesis** / joint lab — contingency table heat; χ² contributions.",
    check: ["df for 3×4 table?", "Does significance prove causation?"],
    formal: "Under H₀ independence, statistic → χ²_{(r−1)(c−1)}.",
    formulas: "- E_{ij}=R_i C_j / n\n- df=(r−1)(c−1)",
    pitfalls: ["Sparse cells", "Overinterpreting association"],
  }),

  buildLesson({
    title: "One-Way ANOVA",
    partLabel: PART,
    principles: [
      "Compare means across ≥3 groups",
      "Partitions variance: between vs within",
      "F = MS_between / MS_within",
      "Assumes roughly normal i.i.d. errors, similar variances",
    ],
    objectives: [
      "State ANOVA hypotheses",
      "Interpret F and p-value",
      "Explain between/within variability",
      "Know post-hoc comparisons are next step",
    ],
    why: "Three teaching methods, three server configs — not just two-sample t.",
    idea: "If group means differ a lot relative to noise inside groups, F is large → reject equal means.",
    steps: [
      { title: "H₀: all μ equal", body: "vs not all equal." },
      { title: "Compute SS/MS", body: "Between and within." },
      { title: "F test", body: "p-value from F distribution." },
    ],
    example: "Exam means 70, 75, 85 across sections with small within variance → significant F.",
    labCue: "**hypothesis** lab — three group clouds; F rises as separation grows.",
    check: ["Why not many pairwise t-tests unchecked?", "What is MS?"],
    formal: "Under H₀ and classical assumptions, F~F_{k−1,n−k}.",
    formulas: "- F=MS_B/MS_W\n- df_B=k−1, df_W=n−k",
    pitfalls: ["Ignoring unequal variances", "Skipping multiple-comparison control after rejection"],
  }),
];
