import { buildLesson } from "./helper.mjs";

const PART = "Part 4: Special Probability Distributions";

export const topics = [
  buildLesson({
    title: "Bernoulli and Binomial Distributions",
    partLabel: PART,
    principles: [
      "Bernoulli: one trial, success/failure",
      "Binomial: count of successes in n independent Bernoulli trials",
      "Parameters n and p fully specify Binomial(n,p)",
      "Mean np, variance np(1−p)",
    ],
    objectives: [
      "Identify Bernoulli vs Binomial settings",
      "Compute binomial probabilities",
      "Use mean and variance formulas",
      "Recognize when independence fails",
    ],
    why: "Click-throughs, bit errors, quiz scores — binary trials and their counts are everywhere.",
    idea: "Bernoulli(p): P(X=1)=p. Binomial(n,p): X=#successes in n i.i.d. Bernoullis; P(X=k)=C(n,k) p^k (1−p)^{n−k}.",
    steps: [
      { title: "Check i.i.d. trials", body: "Same p, independent." },
      { title: "Define success", body: "Binary outcome." },
      { title: "Plug into PMF", body: "Use combinations." },
      { title: "Summarize", body: "E[X]=np, Var=np(1−p)." },
    ],
    example: "10 fair coin flips: P(exactly 6 heads)=C(10,6)/2^{10} ≈ 0.205.",
    labCue: "PMF lab with binomial parameters — slide n and p, watch the mass move.",
    check: ["Is Binomial(1,p) Bernoulli?", "What if trials share dependence?"],
    formal: "X~Bin(n,p) = sum of n i.i.d. Bern(p).",
    formulas: "- P(X=k)=C(n,k)p^k(1−p)^{n−k}\n- E=np, Var=npq",
    pitfalls: ["Using binomial when sampling without replacement (use Hypergeometric)", "Wrong n or p"],
  }),

  buildLesson({
    title: "Geometric and Negative Binomial Distributions",
    partLabel: PART,
    principles: [
      "Geometric: trials until first success",
      "Negative binomial: trials until r successes",
      "Memoryless property of geometric (discrete)",
      "Watch definitions: some texts count failures only",
    ],
    objectives: [
      "Write geometric PMFs under a chosen convention",
      "Compute mean waiting time 1/p",
      "Extend to negative binomial",
      "Apply memorylessness carefully",
    ],
    why: "How many attempts until the first bug fix compiles? Waiting times need geometric-type models.",
    idea: "If P(success)=p each independent trial, waiting time T until first success has P(T=k)=(1−p)^{k−1}p for k=1,2,… and E[T]=1/p.",
    steps: [
      { title: "Fix convention", body: "Support starting at 1 vs 0." },
      { title: "Write PMF", body: "Failures then one success." },
      { title: "Mean", body: "1/p for first-success geometric." },
      { title: "r successes", body: "Negative binomial generalizes." },
    ],
    example: "p=0.2 chance a flaky test passes: expected runs until first pass = 5.",
    labCue: "PMF lab — geometric mode; increase p and see mass shift left.",
    check: ["State memoryless in words.", "Difference geometric vs binomial?"],
    formal: "Memoryless: P(T>s+t|T>s)=P(T>t) for geometric on {1,2,…}.",
    formulas: "- P(T=k)=q^{k−1}p\n- E[T]=1/p, Var=q/p²",
    pitfalls: ["Mixing textbooks' geometric definitions", "Applying memoryless to binomial counts"],
  }),

  buildLesson({
    title: "Poisson Distribution",
    partLabel: PART,
    principles: [
      "Poisson counts rare events in a continuum of opportunity",
      "Single parameter λ = mean = variance",
      "Limit of Binomial(n,p) with np→λ",
      "Models arrivals, defects, clicks per hour",
    ],
    objectives: [
      "Use Poisson PMF e^{−λ} λ^k / k!",
      "Interpret λ",
      "Approximate binomial with Poisson when appropriate",
      "Check mean≈variance empirically",
    ],
    why: "Call centers, packet arrivals, mutation counts — classical rare-event counting.",
    idea: "X~Poisson(λ): P(X=k)=e^{−λ}λ^k/k!, E[X]=Var(X)=λ.",
    steps: [
      { title: "Estimate λ", body: "Average count per interval." },
      { title: "Compute probabilities", body: "PMF or cumulative tables/software." },
      { title: "Validate", body: "Independence of increments / rarity assumptions." },
    ],
    example: "Avg 3 emails/hour. P(0 in an hour)=e^{−3}≈0.05.",
    labCue: "PMF lab — Poisson λ slider; compare to binomial with large n, small p.",
    check: ["Why mean = variance?", "When is Poisson ≈ Binomial?"],
    formal: "Poisson process counts yield Poisson marginals; interarrival times are exponential.",
    formulas: "- P(X=k)=e^{−λ}λ^k/k!\n- E=Var=λ",
    pitfalls: ["Using Poisson when variance ≫ mean (overdispersion)", "Wrong time unit for λ"],
  }),

  buildLesson({
    title: "Uniform Distribution",
    partLabel: PART,
    principles: [
      "Uniform means constant probability/density on a set",
      "Discrete uniform: equal mass on finite points",
      "Continuous Uniform(a,b): f=1/(b−a)",
      "Foundation for random number generation",
    ],
    objectives: [
      "Write discrete and continuous uniform laws",
      "Compute means (a+b)/2",
      "Find interval probabilities by length ratios",
      "Connect to sampling random numbers",
    ],
    why: "Idealized 'no preference' model and the engine behind simulation (transform uniforms).",
    idea: "Continuous U(a,b): flat density. P(X∈I)=length(I∩[a,b])/(b−a).",
    steps: [
      { title: "Identify bounds", body: "a and b." },
      { title: "Density or mass", body: "Constant on support." },
      { title: "Integrate / count", body: "Probability = share of support." },
    ],
    example: "Bus every 10 minutes, you arrive at random: wait ~ U(0,10), expected wait 5 minutes.",
    labCue: "PDF lab — uniform; shade intervals; verify area = length ratio.",
    check: ["E[U(0,1)]?", "Var(U(a,b))?"],
    formal: "Var(U(a,b))=(b−a)²/12.",
    formulas: "- f(x)=1/(b−a) on [a,b]\n- E=(a+b)/2\n- Discrete U{1..n}: p=1/n, E=(n+1)/2",
    pitfalls: ["Using continuous formulas on discrete supports", "Wrong endpoint inclusion (usually moot for continuous)"],
  }),

  buildLesson({
    title: "Normal Distribution",
    partLabel: PART,
    principles: [
      "Bell-shaped, symmetric around μ",
      "Fully specified by mean μ and variance σ²",
      "CLT makes normals ubiquitous",
      "68–95–99.7 rule for σ bands",
    ],
    objectives: [
      "Recognize N(μ,σ²) density",
      "Apply empirical rule",
      "Standardize to Z later",
      "Know PDF formula qualitatively",
    ],
    why: "Measurement error, heights, aggregate noise — the default continuous model.",
    idea: "Symmetric bell centered at μ; σ controls width. About 95% of mass lies in μ±2σ.",
    steps: [
      { title: "Locate μ", body: "Center / peak." },
      { title: "Set σ", body: "Inflection distance ≈ σ." },
      { title: "Shade regions", body: "Use symmetry and known bands or software." },
    ],
    example: "IQ ~ N(100,15²): roughly 68% between 85 and 115.",
    labCue: "PDF lab — normal; change μ and σ; shade μ±σ bands.",
    check: ["Does the normal assign P(X=μ)=0?", "Effect of doubling σ?"],
    formal: "f(x)=(1/(σ√(2π))) exp(−(x−μ)²/(2σ²)).",
    formulas: "- X~N(μ,σ²)\n- 68%/95%/99.7% within 1/2/3 σ",
    pitfalls: ["Assuming normality without checking", "Using ±2σ rules on skewed data"],
  }),

  buildLesson({
    title: "Standard Normal and Z-Scores",
    partLabel: PART,
    principles: [
      "Z=(X−μ)/σ converts any normal to N(0,1)",
      "Z-score = signed number of SDs from the mean",
      "Tables and software give Φ(z)=P(Z≤z)",
      "Comparisons across scales use z-scores",
    ],
    objectives: [
      "Standardize normal problems",
      "Read Φ from tables/software",
      "Interpret z as relative standing",
      "Invert Φ for quantiles",
    ],
    why: "One table/software CDF serves every normal — standardization is the bridge.",
    idea: "If X~N(μ,σ²), then Z=(X−μ)/σ ~ N(0,1). P(X≤x)=Φ((x−μ)/σ).",
    steps: [
      { title: "Write the probability in X", body: "e.g. P(X>90)." },
      { title: "Subtract μ, divide by σ", body: "Get Z bound." },
      { title: "Use Φ", body: "Convert to table value; complement if needed." },
    ],
    example: "X~N(70,10²). P(X<85)=Φ(1.5)≈0.933.",
    labCue: "PDF lab — show original and standardized curves side by side via z toggle.",
    check: ["What is Φ(0)?", "z=−2 means what?"],
    formal: "Φ symmetric: Φ(−z)=1−Φ(z).",
    formulas: "- Z=(X−μ)/σ\n- x=μ+zσ\n- P(a<X<b)=Φ(z_b)−Φ(z_a)",
    pitfalls: ["Using σ² instead of σ in denominator", "Wrong tail direction"],
  }),

  buildLesson({
    title: "Exponential Distribution",
    partLabel: PART,
    principles: [
      "Models waiting times with constant hazard",
      "Memoryless continuous distribution",
      "Linked to Poisson processes",
      "Mean 1/λ, PDF λe^{−λx}",
    ],
    objectives: [
      "Use exponential PDF/CDF",
      "Compute waiting-time probabilities",
      "State continuous memorylessness",
      "Relate λ to Poisson rate",
    ],
    why: "Time-to-failure, time-to-next-request — classic reliability and queueing.",
    idea: "X~Exp(λ): f(x)=λe^{−λx}, F(x)=1−e^{−λx}, E[X]=1/λ. Memoryless: remaining wait forgets the past.",
    steps: [
      { title: "Fit λ", body: "1 / mean wait." },
      { title: "CDF for tails", body: "P(X>t)=e^{−λt}." },
      { title: "Check memoryless story", body: "Does constant hazard make sense?" },
    ],
    example: "Mean interarrival 2 min ⇒ λ=0.5. P(wait > 4)=e^{−2}≈0.135.",
    labCue: "PDF lab — exponential; shade long waits; compare hazard story.",
    check: ["Is Exp memoryless?", "Link to Poisson counts?"],
    formal: "If N(t)~Poisson(λt), waiting time for first event ~ Exp(λ).",
    formulas: "- f(x)=λe^{−λx}\n- F=1−e^{−λx}\n- E=1/λ, Var=1/λ²",
    pitfalls: ["Using exponential for wear-out failures (hazard not constant)", "Confusing λ vs mean parameterization"],
  }),

  buildLesson({
    title: "Gamma and Chi-Square Distributions",
    partLabel: PART,
    principles: [
      "Gamma generalizes exponential sums",
      "Chi-square is Gamma with specific params — key for inference",
      "Sum of squared standard normals → χ²",
      "Appears in variance estimators and goodness-of-fit",
    ],
    objectives: [
      "Describe Gamma shape/rate qualitatively",
      "Recognize χ²_k as sum of k i.i.d. Z²",
      "Know E[χ²_k]=k",
      "Preview use in CI / tests",
    ],
    why: "Sampling distributions for variance and many test statistics are chi-square or gamma-related.",
    idea: "Chi-square with k degrees of freedom: wait for k exponential 'hits' (Erlang) / sum of k squared standard normals. Skewed right; becomes more symmetric as k grows.",
    steps: [
      { title: "Identify df k", body: "How many squared normals?" },
      { title: "Mean = k", body: "Quick check." },
      { title: "Use tables/software", body: "Critical values for tests later." },
    ],
    example: "Z₁,Z₂ i.i.d. N(0,1) ⇒ Z₁²+Z₂² ~ χ²_2, mean 2.",
    labCue: "PDF lab — chi-square; increase df and watch skew fade.",
    check: ["χ²_1 related to N(0,1) how?", "Support of χ²?"],
    formal: "χ²_k = Gamma(k/2, 1/2) under common rate/shape conventions (check parameterization).",
    formulas: "- E[χ²_k]=k, Var=2k\n- (n−1)s²/σ² ~ χ²_{n−1} for normal samples",
    pitfalls: ["Wrong degrees of freedom", "Mixing rate vs scale gamma params"],
  }),

  buildLesson({
    title: "Beta Distribution",
    partLabel: PART,
    principles: [
      "Beta lives on (0,1) — ideal for proportions",
      "Shape parameters α,β flex the density",
      "Conjugate prior for Bernoulli/Binomial in Bayesian stats",
      "Uniform(0,1) is Beta(1,1)",
    ],
    objectives: [
      "Recognize Beta support (0,1)",
      "Interpret α,β as prior pseudo-counts",
      "Sketch U-shaped vs unimodal betas",
      "Preview Bayesian updating",
    ],
    why: "Modeling unknown click rates and probabilities before/after data — Beta is the natural language.",
    idea: "X~Beta(α,β) on (0,1). Large α relative to β pushes mass toward 1. Beta(1,1)=flat prior.",
    steps: [
      { title: "Start with uniform", body: "Beta(1,1)." },
      { title: "Add successes/failures", body: "α↑ or β↑." },
      { title: "Read mean", body: "α/(α+β)." },
    ],
    example: "Prior Beta(2,2) for a coin bias; after 8 heads 2 tails → Beta(10,4), mean 0.71.",
    labCue: "PDF lab — beta; tweak α,β; see mass slide toward 0 or 1.",
    check: ["Support of Beta?", "Mean formula?"],
    formal: "Density ∝ x^{α−1}(1−x)^{β−1} on (0,1).",
    formulas: "- E[X]=α/(α+β)\n- Var=αβ/[(α+β)²(α+β+1)]",
    pitfalls: ["Using Beta outside [0,1] data", "Forgetting conjugacy update α'=α+#successes"],
  }),
];
